'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../dist/findings-core.js');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const row=(id,finding={},extra={})=>({contract:C.CONTRACT,id,source:'letter',status:'accepted',route:'extract',finding:{cat:'bank',act:'review',...finding},evidence:[],checks:{schema_errors:[],grounded:{}},meta:{tier:'L1',model:'base',latency_ms:6000,output_tokens:60},text:'One\r\n\r\nThree\r\n',...extra});
function harness({enabled=true,initial=[],workspace=false,authenticated=true}={}){
 const listeners={},calls=[],saved=new Map(),nodes=new Map(),notices=[];
 let collection=initial,fail=false,html='',modalHTML='',modalCount=0,handler=null;
 const element=()=>({textContent:'',innerHTML:'',value:'',open:false,setAttribute(){},querySelector(){return null},insertAdjacentHTML(){},scrollIntoView(){}});
 nodes.set('#main',element());nodes.set('#detail-dialog',element());nodes.set('#findings-note-status',element());
 const context={console,URL,URLSearchParams,Intl,Date,Map,Set,Array,Object,Number,String,JSON,Math,Promise,Blob,AbortController,Uint8Array,performance,FindingsCore:C,AfterwordRuntime:{offline:true,extraction:enabled,preview:!enabled,workspace,requireLogin:workspace},state:{route:'overview',lang:'en'},location:{origin:'http://127.0.0.1:8010',hash:'#overview'},localStorage:{getItem:key=>saved.get(key)||null,setItem:(key,value)=>saved.set(key,value)},document:{addEventListener:(name,callback)=>(listeners[name]??=[]).push(callback),createElement:()=>({click(){}})},nav:['overview','plan','documents','evidence','letters','memories','exposure','ledger','settings'].map(name=>[name,'files',name]),views:Object.fromEntries(['overview','plan','documents','evidence','letters','memories','exposure','ledger','settings','ask'].map(name=>[name,()=>'<p>Arun fixture '+name+'</p>'])),actions:{'workspace-info':()=>{},command:()=>{}},escapeHTML:value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),icon:()=>'<svg></svg>',heading:(a,b,c,d='')=>`<header><h1>${b}</h1><p>${c}</p>${d}</header>`,$:selector=>nodes.get(selector)||null,formatDate:value=>value,formatTime:value=>value,toast:text=>notices.push(text),afterRender:()=>{},prepareRoute:()=>{},closeDialog:()=>{nodes.get('#detail-dialog').open=false;},modal:(title,body)=>{modalHTML=title+body;modalCount++;nodes.get('#detail-dialog').open=true;nodes.set('#findings-intake-progress',element());},setTimeout:()=>1,clearTimeout:()=>{},btoa:text=>Buffer.from(text,'binary').toString('base64'),render:()=>{context.prepareRoute?.();html=context.views[context.state.route]();context.afterRender();},go:route=>{context.location.hash='#'+route;context.state.route=route.split('?')[0];context.render();},fetch:async(url,options={})=>{const u=new URL(url);calls.push({path:u.pathname+u.search,body:options.body?JSON.parse(options.body):null});if(handler){const value=await handler(u,options);if(value)return value;}if(fail)throw Error('Device disconnected');const value=u.pathname==='/health'?{contract:C.CONTRACT,capabilities:{extract:true},model:'base',offline:true,telemetry:{entities_sent_to_cloud:0,cloud_equivalent_cost:null,scope:'current_offline_application',basis:'External integrations disabled; model and OCR processing confined to this device.'}}:u.pathname==='/findings'?{contract:C.CONTRACT,findings:collection,total:collection.length}:{};return {ok:true,json:async()=>value};}};
 context.addEventListener=(name,callback)=>(listeners[name]??=[]).push(callback);context.AfterwordProfile={canAccessData:()=>authenticated,lock:()=>{authenticated=false;context.closeDialog();for(const fn of listeners['afterword-locked']||[])fn();}};
 context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('dist/findings.js','utf8'),context);
 return {context,calls,saved,nodes,notices,setAuth:value=>{authenticated=value},get html(){return html},get modalHTML(){return modalHTML},get modalCount(){return modalCount},setRows:value=>{collection=value},setFail:value=>{fail=value},setHandler:value=>{handler=value},view:name=>{context.state.route=name;context.location.hash='#'+name;context.render();return html},evidence:id=>{context.location.hash='#evidence?finding='+encodeURIComponent(id);context.render();return html},event:(type,target)=>listeners[type]?.forEach(callback=>callback({target})),action:(name,dataset={})=>context.actions[name]({dataset})};
}
(async()=>{
 const malicious='<img src=x onerror=alert(1)>',rows=[row('__proto__',{inst:malicious,amt:0,money_at_stake:0,due:30},{reference_date:'2026-09-01',evidence:[{line:3,text:'Three'}]}),row('early',{inst:'Earliest bank',amt:10,money_at_stake:20,due:0}),row('memory',{cat:'personal'},{route:'memory',text:'A private source phrase that must never be translated'}),row('ignored',{cat:'irrelevant'},{route:'drop'}),row('failure',{}, {status:'failed',route:null,finding:null,checks:{error:'Model not available'}})];
 const h=harness({initial:rows});await tick();await tick();
 assert.equal(h.context.AfterwordFindings.summary().documents,5);
 assert.doesNotMatch(h.html,/Arun fixture/);
 let html=h.view('plan');assert.ok(html.indexOf('Earliest bank')<html.indexOf('&lt;img'));assert.match(html,/Printed amount/);assert.match(html,/What’s at stake/);assert.match(html,/>0<\/strong>/);assert.match(html,/1 irrelevant item ignored/);assert.match(html,/Model not available/);assert.doesNotMatch(html,/<img|\$20/);
 html=h.evidence('__proto__');assert.match(html,/Line 3/);assert.match(html,/class="is-cited"/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img/);assert.match(html,/Calendar date not returned/);
 h.event('input',{id:'findings-note',dataset:{id:'__proto__'},value:'My note'});
 const stored=JSON.parse(h.saved.get('afterword-finding-notes-v1'));assert.equal(stored[0][0],'__proto__');assert.equal(stored[0][1].note,'My note');assert.doesNotMatch(h.saved.get('afterword-finding-notes-v1'),/Three|private source/);
 h.action('findings-read',{id:'__proto__'});assert.match(h.html,/Read · Undo/);assert.match(h.html,/Accepted/,'Reading must not rewrite the model status.');
 html=h.evidence('not-in-archive');assert.match(html,/No record selected/);assert.doesNotMatch(html,/Earliest bank/,'An unknown deep link must not silently open another source.');
 html=h.view('memories');assert.match(html,/private source phrase/);assert.doesNotMatch(html,/Earliest bank|ignored/);
 const translated=[];h.context.translatedBlock=(text)=>{translated.push(text);return '';};h.evidence('memory');assert.ok(translated.length);assert.ok(translated.every(text=>!text.includes('private source phrase')),'Raw documents are not sent for translation.');
 html=h.view('ledger');assert.match(html,/Escalation Ledger/);assert.match(html,/60/);assert.match(html,/6,000 ms/);assert.match(html,/Cloud-equivalent cost<\/dt><dd>Not available/);assert.match(html,/Entities sent to cloud<\/dt><dd>0/);
 assert.match(html,/application’s processing boundary/);assert.match(html,/Whole-device traffic/);assert.match(html,/External integrations disabled/);
 h.setHandler(async u=>u.pathname==='/health'?{ok:true,json:async()=>({contract:C.CONTRACT,capabilities:{extract:true},offline:true,telemetry:{entities_left_device:0}})}:null);await h.context.AfterwordFindings.refresh();assert.match(h.view('ledger'),/Entities sent to cloud<\/dt><dd>Not available/,'Legacy whole-device field does not imply no cloud uploads.');
 h.setHandler(async u=>u.pathname==='/health'?{ok:true,json:async()=>({contract:C.CONTRACT,capabilities:{extract:true},offline:true,telemetry:{entities_sent_to_cloud:0,scope:'unknown'}})}:null);await h.context.AfterwordFindings.refresh();assert.match(h.view('ledger'),/Entities sent to cloud<\/dt><dd>Not available/,'Count requires an explicit application scope.');h.setHandler(null);await h.context.AfterwordFindings.refresh();
 h.setFail(true);await h.context.AfterwordFindings.refresh();assert.equal(h.context.AfterwordFindings.summary().documents,5);html=h.view('documents');assert.match(html,/last loaded records remain/);assert.match(html,/Earliest bank/);assert.doesNotMatch(html,/Arun fixture/);h.setFail(false);
 h.setRows([row('dup'),row('dup')]);await h.context.AfterwordFindings.refresh();assert.equal(h.context.AfterwordFindings.summary().documents,5);assert.match(h.context.AfterwordFindings.summary().error,/duplicate/);
 h.setRows(rows);await h.context.AfterwordFindings.refresh();
 h.setHandler(async(u)=>u.pathname==='/extract'?{ok:true,json:async()=>rows[0]}:null);await h.action('findings-retry',{id:'__proto__'});const retry=h.calls.find(call=>call.path==='/extract?retry=true');assert.equal(retry.body.reference_date,'2026-09-01');assert.equal(retry.body.text,rows[0].text);
 h.setHandler(null);h.action('findings-preview');assert.match(h.html,/Arun fixture/,'Fictional data requires explicit preview.');assert.equal(h.context.AfterwordFindings.active(),false);h.action('findings-live');await tick();await tick();assert.equal(h.context.AfterwordFindings.active(),true);
 const staticPreview=harness({enabled:false});await tick();assert.equal(staticPreview.calls.length,0,'Static preview makes no extraction requests.');assert.equal(staticPreview.context.AfterwordFindings.active(),false);
 const emptyLive=harness();await tick();await tick();assert.match(emptyLive.view('documents'),/Start with the records/);assert.doesNotMatch(emptyLive.html,/Arun fixture/);
 const rawFailure='URLError: <urlopen error [Errno 61] Connection refused>',failedID='upload-'+ 'a'.repeat(64);
 const failedView=harness({initial:[row(failedID,{}, {status:'failed',route:null,finding:null,text:'\r\nSubject: Storage renewal\r\nOriginal body',checks:{error:rawFailure}})]});await tick();await tick();const failureHTML=failedView.evidence(failedID);assert.match(failureHTML,/<h1>Storage renewal<\/h1>/);assert.match(failureHTML,/The local model is unavailable/);assert.match(failureHTML,/<details class="finding-technical"><summary>Technical details<\/summary>/);assert.match(failureHTML,/&lt;urlopen error/);assert.match(failureHTML,new RegExp('<dd>'+failedID+'<\/dd>'));assert.equal(failedView.context.AfterwordFindings.getRecord(failedID).checks.error,rawFailure);
 const ungroundedRecord=row('ungrounded',{inst:'Harbor Club',due:0,deadline_date:'2026-09-01',amt:0,money_at_stake:0},{status:'needs_review',checks:{schema_errors:[],grounded:{due:false,amt:false}}});
 const provisional=harness({initial:[ungroundedRecord]});await tick();await tick();let provisionalHTML=provisional.view('overview');assert.match(provisionalHTML,/Model-returned date · verify against source/);assert.doesNotMatch(provisionalHTML,/days past the stated date|days remaining/);assert.match(provisionalHTML,/Printed amount · unverified/);assert.match(provisionalHTML,/What’s at stake · provisional/);assert.match(provisionalHTML,/Based on an unverified amount/);assert.match(provisionalHTML,/>0<\/strong>/);assert.equal(provisional.context.AfterwordFindings.getRecord('ungrounded').finding.deadline_date,'2026-09-01');assert.equal(provisional.context.AfterwordFindings.getRecord('ungrounded').finding.due,0);
 provisional.setRows([row('schema-date',{due:0,deadline_date:'2026-09-01'},{checks:{schema_errors:["'due' not an integer"],grounded:{due:true}}})]);await provisional.context.AfterwordFindings.refresh();assert.match(provisional.evidence('schema-date'),/Model-returned date · verify against source/);
 provisional.setRows([row('relative',{due:0},{checks:{schema_errors:[],grounded:{due:false}}})]);await provisional.context.AfterwordFindings.refresh();assert.match(provisional.evidence('relative'),/Model returned 0 days/);assert.doesNotMatch(provisional.html,/days stated in the record/);
 provisional.setRows([row('verified-date',{due:0,deadline_date:'2026-09-01',amt:0,money_at_stake:0},{checks:{schema_errors:[],grounded:{due:true,amt:true}}})]);await provisional.context.AfterwordFindings.refresh();assert.doesNotMatch(provisional.evidence('verified-date'),/Model-returned date|amount · unverified|stake · provisional/);
 // The live PDF export preserves the same relative deadlines and amount
 // comparison as the cards, including uncertainty, recurrence and real zeros.
 const exportRows=[row('monthly',{due:30,amt:25,money_at_stake:300,rec:'monthly'}),row('relative-zero',{due:0,amt:0,money_at_stake:0,rec:'monthly'},{status:'needs_review',checks:{schema_errors:[],grounded:{due:false,amt:false}}}),ungroundedRecord,row('unknown',{amt:0,money_at_stake:null,deadline_date:'09/25/2026'})];
 const exportBefore=JSON.stringify(exportRows),pdf=harness({initial:exportRows});await tick();await tick();let report;
 pdf.context.AfterwordReports={downloadPlan:async value=>{report=value;}};await pdf.action('findings-export-plan');
 const exported=id=>report.items.find(item=>item.id===id);
 assert.equal(exported('monthly').date,'30 days stated in the record · No reference date supplied');
 assert.equal(exported('monthly').amount,'Printed amount: 25; calculated amount at stake: 300; recurrence: monthly. Currency from source.');
 assert.match(exported('relative-zero').date,/Model returned 0 days · Verify against the source/);assert.doesNotMatch(exported('relative-zero').date,/days stated in the record/);
 assert.match(exported('relative-zero').amount,/Printed amount \(unverified\): 0; calculated amount at stake \(provisional\): 0; recurrence: monthly/);
 assert.equal(exported('ungrounded').date,'2026-09-01 · Model-returned date; verify against source');
 assert.equal(exported('unknown').date,'No stated deadline');assert.match(exported('unknown').amount,/Printed amount: 0; calculated amount at stake: Not supplied/);
 assert.doesNotMatch(report.items.map(item=>item.amount).join(' '),/\$/,'Exports must not invent a currency.');
 assert.equal(JSON.stringify(exportRows),exportBefore,'Exporting must not rewrite engine fields.');
 pdf.event('change',{id:'findings-status',value:'needs_review'});await pdf.action('findings-export-plan');assert.equal(report.items.length,2,'Export keeps the current plan filters.');
 // Real intake handlers: upload preview -> sequential extraction; retry only failed IDs.
 const upload=harness();await tick();await tick();let extractions=0;upload.setHandler(async(u,options)=>{
  const body=options.body?JSON.parse(options.body):{};
  if(u.pathname==='/ingest/preview')return {ok:true,json:async()=>({documents:[{id:'mail-1',warnings:[]}],errors:[],document_count:1})};
  if(u.pathname==='/ingest/extract'){extractions++;assert.equal(body.content_base64,Buffer.from('mail').toString('base64'));return {ok:true,json:async()=>({results:[row('mail-1',{},extractions===1?{status:'failed'}:{})],errors:[]})};}return null;
 });upload.action('findings-import');upload.event('change',{id:'findings-files',files:[{name:'one.eml',size:4,arrayBuffer:async()=>Uint8Array.from(Buffer.from('mail')).buffer}]});await tick();await tick();assert.match(upload.modalHTML,/1 records ready/);await upload.action('findings-intake-start');assert.match(upload.modalHTML,/need another attempt/);await upload.action('findings-intake-start');const requests=upload.calls.filter(call=>call.path.startsWith('/ingest/extract'));assert.equal(requests[0].path,'/ingest/extract');assert.equal(requests[1].path,'/ingest/extract?retry=true');assert.deepEqual(requests[1].body.document_ids,['mail-1']);
 // Subset model retries retain parser errors for unselected records until that ID parses.
 const partial=harness();await tick();await tick();let attempts=0;const parserError={id:'broken-page',position:2,message:'Page 2 cannot be read',retryable:true};partial.setHandler(async(u)=>{
  if(u.pathname==='/ingest/preview')return {ok:true,json:async()=>({documents:[{id:'mail-1',warnings:[]}],errors:[parserError],document_count:1})};
  if(u.pathname==='/ingest/extract'){attempts++;const subset=attempts===2;return {ok:true,json:async()=>({documents:[{id:'mail-1'},...(attempts===3?[{id:'broken-page'}]:[])],results:[row('mail-1',{},attempts===1?{status:'failed'}:{}),...(attempts===3?[row('broken-page')]:[])],errors:subset||attempts===3?[]:[parserError]})};}return null;
 });partial.action('findings-import');partial.event('change',{id:'findings-files',files:[{name:'mixed.mbox',size:4,arrayBuffer:async()=>Uint8Array.from(Buffer.from('mail')).buffer}]});await tick();await tick();await partial.action('findings-intake-start');assert.match(partial.modalHTML,/Page 2 cannot be read/);await partial.action('findings-intake-start');assert.match(partial.modalHTML,/Page 2 cannot be read/,'Unselected parser error survives successful model retry.');assert.match(partial.modalHTML,/1 parser errors/);await partial.action('findings-intake-start');assert.doesNotMatch(partial.modalHTML,/Page 2 cannot be read/,'Only exact record parser recovery clears the error.');assert.match(partial.modalHTML,/2 records processed/);const partialCalls=partial.calls.filter(call=>call.path.startsWith('/ingest/extract'));assert.deepEqual(partialCalls[1].body.document_ids,['mail-1']);assert.equal(partialCalls[2].body.document_ids,undefined,'Remaining parser failures trigger idempotent reparse, retaining prior extraction results.');
 // Cancel lets the current file finish and prevents the next file from starting.
 const stopped=harness();await tick();await tick();let finishCurrent,started=0;stopped.setHandler(async(u)=>{
  if(u.pathname==='/ingest/preview')return {ok:true,json:async()=>({documents:[{id:'item',warnings:[]}],errors:[],document_count:1})};
  if(u.pathname==='/ingest/extract'){started++;return new Promise(resolve=>{finishCurrent=()=>resolve({ok:true,json:async()=>({results:[row('item')],errors:[]})});});}return null;
 });stopped.action('findings-import');stopped.event('change',{id:'findings-files',files:['first.eml','second.eml'].map(name=>({name,size:4,arrayBuffer:async()=>Uint8Array.from(Buffer.from('mail')).buffer}))});await tick();await tick();
 const processing=stopped.action('findings-intake-start');await tick();assert.equal(started,1);stopped.action('findings-intake-stop');finishCurrent();await processing;assert.equal(started,1,'Cancel must not begin the second file.');assert.match(stopped.modalHTML,/records processed/);assert.match(stopped.modalHTML,/records ready/);
 // Closing while a preview is in flight must not reopen the dialog when its response arrives.
 let finish;upload.setHandler(async u=>u.pathname==='/ingest/preview'?new Promise(resolve=>{finish=()=>resolve({ok:true,json:async()=>({documents:[],errors:[],document_count:0})});}):null);upload.event('change',{id:'findings-files',files:[{name:'two.eml',size:4,arrayBuffer:async()=>Uint8Array.from(Buffer.from('mail')).buffer}]});await tick();upload.context.closeDialog();const before=upload.modalCount;finish();await tick();await tick();assert.equal(upload.modalCount,before);assert.equal(upload.nodes.get('#detail-dialog').open,false);
 // Authentication blocks the initial fetch, clears display caches and rejects stale replies.
 const locked=harness({workspace:true,authenticated:false,initial:[row('private')]});await tick();assert.equal(locked.calls.length,0);
 locked.setAuth(true);await locked.context.AfterwordFindings.refresh();assert.equal(locked.context.AfterwordFindings.summary().documents,1);
 locked.event('input',{id:'findings-note',dataset:{id:'private'},value:'Private review note'});
 let finishArchive;locked.setHandler(async u=>u.pathname==='/findings'?new Promise(resolve=>{finishArchive=()=>resolve({ok:true,json:async()=>({contract:C.CONTRACT,findings:[row('stale')],total:1})});}):null);
 const staleArchive=locked.context.AfterwordFindings.refresh();await tick();locked.context.AfterwordProfile.lock();finishArchive();await staleArchive;
 assert.equal(locked.context.AfterwordFindings.summary().documents,0,'A response from before logout cannot restore private records.');
 assert.equal(locked.context.AfterwordFindings.getRecord('private'),undefined);
 assert.doesNotMatch(locked.view('documents'),/Private review note/);
 assert.ok(locked.saved.get('afterword-finding-notes-v1').includes('Private review note'),'Lock preserves saved notes for the authenticated user.');
 locked.setHandler(null);locked.setAuth(true);await locked.context.AfterwordFindings.refresh();assert.match(locked.evidence('private'),/Private review note/);
 locked.setHandler(async u=>u.pathname==='/findings'?{ok:false,status:401,json:async()=>({detail:'Sign in to continue.'})}:null);
 await locked.context.AfterwordFindings.refresh();assert.equal(locked.context.AfterwordFindings.summary().documents,0,'401 clears stale records instead of treating it as a temporary outage.');
 console.log('Findings UI: live routes, safe evidence, notes, outage preservation, explicit preview, telemetry, retry and intake handlers passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
