const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const memory = new Map();
let failWrites = false;
const context = vm.createContext({localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{if(failWrites)throw Error('quota');memory.set(k,v);}}});
vm.runInContext(fs.readFileSync('dist/store.js','utf8')+'\nthis.store = AfterwordStore;',context);
const store = context.store;
const clean = v=>JSON.parse(JSON.stringify(store.clean(v)));

assert.deepEqual(clean({completed:null,waiting:{},favorite:false}).completed,['notify-employer','gather-records']);
assert.deepEqual(clean({completed:['insurance','insurance','unknown'],waiting:['insurance','storage']}).waiting,['storage']);
assert.equal(clean({largeText:'false',imported:'true'}).largeText,false);
assert.deepEqual(clean(JSON.parse('{"drafts":{"__proto__":{"name":"x"}},"__proto__":{"polluted":true}}')).drafts,{});
assert.equal({}.polluted,undefined);
const legacy={template:'medical',name:'Priya',recipient:'Sample clinic',subject:'Balance',body:'Please confirm.'};
assert.equal(clean({savedDraft:legacy}).drafts.medical.subject,'Balance');
assert.equal(clean({savedDraft:legacy}).lastDraft,'medical');
assert.equal(clean({lastDraft:'constructor'}).lastDraft,'insurance');
assert.equal(clean({drafts:{insurance:{name:'',recipient:'',subject:'Unfinished',body:''}}}).drafts.insurance.subject,'Unfinished');
assert.deepEqual(clean({savedDraft:{...legacy,template:'constructor'}}).drafts,{});
assert.equal(clean({taskNotes:{insurance:'x'.repeat(3000)}}).taskNotes.insurance.length,2000);
assert.deepEqual(clean({reminders:{insurance:'2026-02-30',storage:'2026-10-02'}}).reminders,{storage:'2026-10-02'});
assert.equal(store.validDate('2026-02-29'),false);
assert.equal(store.validDate('2028-02-29'),true);
assert.equal(store.validateFile({name:'sample.txt',size:123}), '');
assert.match(store.validateFile({name:'sample.html',size:123}),/Use a PDF/);
assert.match(store.validateFile({name:'empty.pdf',size:0}),/empty/);
assert.match(store.validateFile({name:'large.pdf',size:21*1024*1024}),/20 MB/);
assert.equal(clean({staged:[{id:'<script>',name:'bad',size:123}]}).staged.length,0);
assert.deepEqual(clean({reviewTimes:{insurance:'yesterday'}}).reviewTimes,{});
memory.set('afterword-workspace-v3','{broken json');
assert.equal(store.load().completed.length,2);
memory.delete('afterword-workspace-v3');
memory.set('afterword-design-v2',JSON.stringify({savedDraft:legacy}));
assert.equal(store.load().drafts.medical.body,'Please confirm.');
assert.equal(store.save({favorite:['tea']}),true);
assert.equal(store.load().favorite[0],'tea');
failWrites=true;
assert.equal(store.save({favorite:[]}),false);
console.log('State validation passed: corruption, migration, ID allowlists, bounds, dates, file validation and unavailable storage.');
