const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const memory = new Map();
let failWrites = false;
const context = vm.createContext({localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{if(failWrites)throw Error('quota');memory.set(k,v);}}});
vm.runInContext(fs.readFileSync('dist/store.js','utf8')+'\nthis.store = AfterwordStore;',context);
const store = context.store;
const clean = v=>JSON.parse(JSON.stringify(store.clean(v)));

assert.deepEqual(clean({completed:null,waiting:{},favorite:false}).completed,['notify-employer','gather-records']);
assert.deepEqual(clean({completed:['insurance','insurance','unknown'],waiting:['insurance','storage']}).waiting,['storage']);
assert.deepEqual(clean({outreachReview:['storage','unknown','storage'],completed:['medical'],waiting:['insurance']}).outreachReview,['storage']);
assert.deepEqual(clean({outreachReview:['insurance','medical','storage'],completed:['medical'],waiting:['insurance']}).outreachReview,['storage']);
assert.equal(clean({largeText:'false',imported:'true'}).largeText,false);
assert.equal(clean({}).ambientMotion,true);
assert.equal(clean({ambientMotion:false}).ambientMotion,false);
assert.equal(clean({ambientMotion:'false'}).ambientMotion,true);
assert.equal(clean({}).theme,'system');
assert.equal(clean({theme:'dark'}).theme,'dark');
assert.equal(clean({theme:'sepia'}).theme,'system');
assert.deepEqual(clean(JSON.parse('{"drafts":{"__proto__":{"name":"x"}},"__proto__":{"polluted":true}}')).drafts,{});
assert.equal({}.polluted,undefined);
const legacy={template:'medical',name:'Priya',recipient:'Sample clinic',subject:'Balance',body:'Please confirm.'};
assert.equal(clean({savedDraft:legacy}).drafts.medical.subject,'Balance');
assert.equal(clean({savedDraft:legacy}).lastDraft,'medical');
assert.equal(clean({lastDraft:'constructor'}).lastDraft,'insurance');
assert.equal(clean({drafts:{insurance:{name:'',recipient:'',subject:'Unfinished',body:''}}}).drafts.insurance.subject,'Unfinished');
assert.deepEqual(clean({savedDraft:{...legacy,template:'constructor'}}).drafts,{});
assert.equal(clean({taskNotes:{insurance:'x'.repeat(3000)}}).taskNotes.insurance.length,2000);
assert.deepEqual(clean({reminders:{insurance:'2026-02-30',storage:'2026-10-02'}}).reminders,{storage:'2026-10-02'});
assert.equal(store.validDate('2026-02-29'),false);
assert.equal(store.validDate('2028-02-29'),true);
assert.equal(store.validateFile({name:'sample.txt',size:123}), '');
assert.match(store.validateFile({name:'sample.html',size:123}),/Use a PDF/);
assert.match(store.validateFile({name:'empty.pdf',size:0}),/empty/);
assert.match(store.validateFile({name:'large.pdf',size:21*1024*1024}),/20 MB/);
assert.equal(clean({staged:[{id:'<script>',name:'bad',size:123}]}).staged.length,0);
assert.deepEqual(clean({reviewTimes:{insurance:'yesterday'}}).reviewTimes,{});
assert.equal(clean({}).lang,'en');
assert.equal(clean({lang:'hi'}).lang,'hi');
assert.equal(clean({lang:'fr'}).lang,'en');
assert.equal(clean({lang:'__proto__'}).lang,'en');
memory.set('afterword-workspace-v3','{broken json');
assert.equal(store.load().completed.length,2);
memory.delete('afterword-workspace-v3');
memory.set('afterword-design-v2',JSON.stringify({savedDraft:legacy}));
assert.equal(store.load().drafts.medical.body,'Please confirm.');
assert.equal(store.load().lang,'en');
assert.equal(store.save({favorite:['tea']}),true);
assert.equal(store.load().favorite[0],'tea');
assert.equal(store.save({ambientMotion:false}),true);
assert.equal(store.load().ambientMotion,false);
failWrites=true;
assert.equal(store.save({favorite:[]}),false);
// A host without the HP account service (GitHub Pages, the offline runtime) keeps the
// browser-local prototype without an outage warning; a failing service is still reported.
(async () => {
  const remote = status => {
    const ctx = vm.createContext({localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},window:{dispatchEvent(){}},CustomEvent:class{},
      fetch:async()=>({ok:status<400,status,json:async()=>({csrf_token:'test',state:{}})})});
    vm.runInContext(fs.readFileSync('dist/store.js','utf8')+'\nthis.store = AfterwordStore;',ctx);
    return ctx.store;
  };
  const calls = [];
  await remote(404).enableRemote(() => calls.push('load'), () => calls.push('error'));
  assert.deepEqual(calls, [], 'A host without the account service stays browser-local without an outage warning.');
  await remote(503).enableRemote(() => calls.push('load'), () => calls.push('error'));
  assert.deepEqual(calls, ['error'], 'A failing account service is still reported.');
  console.log('State validation passed: corruption, migration, ID allowlists, bounds, dates, file validation, unavailable storage and the static-host fallback.');
})().catch(error => { console.error(error); process.exit(1); });
