"""Write dist/data/drain_snapshot.json: GET /drain results for the static GitHub Pages site.

The public site has no server, so it shows figures the backend computed here,
one variant per combination of completed charge-bearing tasks. No date of death
is included; adding one needs the local service. Run after changing the
archive, rules or drain logic; `--check` fails if the committed file is stale.
"""
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from backend.buckets import BucketClassifier  # noqa: E402
from backend.drain import RULES_PATH, compute_drain, parse_date  # noqa: E402

OUTPUT = ROOT / 'dist/data/drain_snapshot.json'


def build():
    archive = json.loads((ROOT / 'data/demo_archive.json').read_text())
    directory = {p['provider_id']: p for p in json.loads((ROOT / 'data/providers_directory.json').read_text())['providers']}
    classifier = BucketClassifier.from_file(RULES_PATH, model=None)
    as_of = max(parse_date(d['date']) for d in archive['documents'] if d.get('date'))

    def run(done=()):
        return compute_drain(archive['documents'], archive['findings'], directory, classifier, done=done, as_of=as_of)
    base = run()
    ids = sorted({l['finding_id'] for l in base['buckets']['stoppable'] if l['finding_id']})
    variants = {}
    for size in range(len(ids) + 1):
        for combo in itertools.combinations(ids, size):
            variants[','.join(combo)] = run(combo)
    return {
        'version': 1,
        'notice': 'Generated by scripts/drain_snapshot.py from the fictional archive with backend/drain.py. Keyed by completed task ids. No date of death is included.',
        'variant_ids': ids,
        'variants': variants,
    }


def render():
    return json.dumps(build(), indent=1, ensure_ascii=False) + '\n'


if __name__ == '__main__':
    if '--check' in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != render():
            raise SystemExit('dist/data/drain_snapshot.json is stale. Run: python scripts/drain_snapshot.py')
        print('Drain snapshot matches the backend computation.')
    else:
        OUTPUT.write_text(render())
        print('Wrote', OUTPUT.relative_to(ROOT))
