"""Phase 8: builds dist/ui-strings.js, the whole-page translation dictionary.

Takes ui_strings_source.json (from crawl_ui_strings.py), sends every string
through the same pipeline as POST /translate (do_translate, in-process: token
protection, retry, round-trip check, SQLite cache), then gates each result:

  rejected (stays English on screen):
    - a protected value (amount, date, name, account number) is missing
    - sentinel syntax (⟦...⟧) survived into the text
    - Hindi output with no Devanagari at all (the model answered in English)
  flagged for review (used, but listed in the report):
    - low round-trip confidence, or length far off the source

Hand corrections live in ui_strings_overrides.json ({lang: {source: text}})
and always win, so a rerun never undoes a review. Writes after each language,
so the page can be checked in Spanish while Hindi is still generating.

  cd backend && /home/hp24/miniforge3/envs/zgx/bin/python dev/gen_ui_strings.py
"""
import json
import re
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import app as backend  # noqa: E402
from translate import SENTINEL_RE, protect  # noqa: E402

SOURCE = HERE / 'ui_strings_source.json'
OVERRIDES = HERE / 'ui_strings_overrides.json'
REPORT = HERE / 'ui_strings_report.json'
OUT = HERE.parents[1] / 'dist' / 'ui-strings.js'
LANGS = ['es', 'vi', 'hi']
DEVANAGARI = re.compile(r'[ऀ-ॿ]')


def needs_translation(text):
    # Strings that are nothing but protected values ("Arun Rao", "Sep 24")
    # would come back unchanged; skip the model call.
    masked, _ = protect(text)
    return bool(re.search(r'[A-Za-z]', SENTINEL_RE.sub('', masked)))


def check(source, lang, result):
    """Returns (verdict, reasons): verdict is 'ok', 'flag' or 'reject'."""
    text, reject, flag = result.text, [], []
    _, tokens = protect(source)
    missing = [t.value for t in tokens if t.value not in text]
    if missing:
        reject.append(f'protected value missing: {missing}')
    if '⟦' in text or '⟧' in text:
        reject.append('sentinel syntax in output')
    if lang == 'hi' and not DEVANAGARI.search(text):
        reject.append('no Devanagari in Hindi output')
    if result.low_confidence:
        flag.append(f'round-trip {result.round_trip_score:.2f}')
    if len(source) > 12 and not 0.4 <= len(text) / len(source) <= 3.5:
        flag.append(f'length ratio {len(text) / len(source):.2f}')
    if reject:
        return 'reject', reject + flag
    return ('flag' if flag else 'ok'), flag


def write(dictionary, report):
    body = json.dumps(dictionary, ensure_ascii=False, sort_keys=True, indent=1)
    OUT.write_text('/* Generated by backend/dev/gen_ui_strings.py from ui_strings_source.json.\n'
                   '   Do not edit by hand -- corrections go in ui_strings_overrides.json. */\n'
                   f'window.AFTERWORD_UI_STRINGS = {body};\n')
    REPORT.write_text(json.dumps(report, ensure_ascii=False, indent=1))


def main():
    backend.init_db()
    sources = json.loads(SOURCE.read_text())
    overrides = json.loads(OVERRIDES.read_text()) if OVERRIDES.exists() else {}
    todo = [s for s in sources if needs_translation(s)]
    if len(sys.argv) > 1:  # smoke test: `gen_ui_strings.py 5` does the first 5 only
        todo = todo[:int(sys.argv[1])]
    print(f'{len(sources)} strings, {len(todo)} need translating', flush=True)

    dictionary, report = {}, {}
    for lang in LANGS:
        dictionary[lang], report[lang] = {}, {}
        t0 = time.time()
        for i, source in enumerate(todo, 1):
            result = backend.do_translate(source, lang, 'instruction')
            verdict, reasons = check(source, lang, result)
            report[lang][source] = {'text': result.text, 'verdict': verdict, 'reasons': reasons,
                                    'round_trip_score': round(result.round_trip_score, 3)}
            if verdict != 'reject' and result.text != source:
                dictionary[lang][source] = result.text
            if i % 50 == 0:
                print(f'  {lang} {i}/{len(todo)} ({time.time() - t0:.0f}s)', flush=True)
        for source, text in overrides.get(lang, {}).items():
            dictionary[lang][source] = text
            report[lang].setdefault(source, {})['override'] = text
        write(dictionary, report)
        counts = {v: sum(r.get('verdict') == v for r in report[lang].values()) for v in ('ok', 'flag', 'reject')}
        print(f'{lang} done in {time.time() - t0:.0f}s: {counts}, {len(dictionary[lang])} entries', flush=True)


if __name__ == '__main__':
    main()
